steps:
  install:
    image: node:22-alpine
    commands:
      - npm ci
  lint-types:
    image: node:22-alpine
    commands:
      - npm run lint:types
  lint-js:
    image: node:22-alpine
    commands:
      - npm run lint:js
  lint-format: 
    image: node:22-alpine
    commands:
      - npm run lint:format
  test:
    image: node:22-alpine
    commands:
      - npm run test
when:
  event: pull_request
