steps:
  install:
    image: node:22
    commands:
      - npm ci
  typecheck:
    image: node:22
    commands:
      - npm run typecheck
  lint-ts:
    image: node:22
    commands:
      - npm run lint:ts
  test:
    image: node:22
    commands:
      - npm run test
when:
  event: pull_request
